### PR TITLE
Feature/made base form class

### PR DESCRIPTION
**Pull request by jstacoder**
added base field class to add attrs to fields, and pulled in html5 field types

### CODE REVIEW

**Comment by tanrax** [comment]
What is the purpose of modifying forms.py?

**Comment by jstacoder** [comment]
the changes in forms.py allow the form macro from my other commit to work. i forgot they were so closely related. i added this to allow setting the field attributes in the field class instantiation, so the macro can dynamically render the form fields, while still applying the html attributes for it to look correct, ie: `class="form-control"` etc...

**Comment by tanrax** [comment]
I have used some of your code. I have learned so much with your pulls. Thx!

**Comment by jstacoder** [comment]
👍  no worries, im sure i will try to refactor this more lol

**Pull request closed without merging**
